// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SpeciFire.UnitTests.TestUtilities._Contact;
using System;

namespace SpeciFire.UnitTests.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("SpeciFire.UnitTests.TestUtilities._Contact.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SpeciFire.UnitTests.TestUtilities._Contact.Contact", b =>
                {
                    b.OwnsOne("SpeciFire.UnitTests.TestUtilities._Contact.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ContactId");

                            b1.Property<string>("City");

                            b1.Property<string>("Email");

                            b1.Property<string>("Phone");

                            b1.ToTable("Contacts");

                            b1.HasOne("SpeciFire.UnitTests.TestUtilities._Contact.Contact")
                                .WithOne("Address")
                                .HasForeignKey("SpeciFire.UnitTests.TestUtilities._Contact.Address", "ContactId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("SpeciFire.UnitTests.TestUtilities._Contact.Name", "Name", b1 =>
                        {
                            b1.Property<int>("ContactId");

                            b1.Property<string>("FirstName");

                            b1.Property<string>("LastName");

                            b1.ToTable("Contacts");

                            b1.HasOne("SpeciFire.UnitTests.TestUtilities._Contact.Contact")
                                .WithOne("Name")
                                .HasForeignKey("SpeciFire.UnitTests.TestUtilities._Contact.Name", "ContactId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
